FROM postgres:12 as postgresdb
WORKDIR /app

# RUN bash -c  'mkdir -p ./scripts/db'
# COPY ./scripts/db/dump.sql /.

# COPY ./scripts/db/ ./
COPY ./scripts/db/init.sh /docker-entrypoint-initdb.d
RUN chmod +x /docker-entrypoint-initdb.d/init.sh

# COPY ./scripts/db/dump.sql ./scripts/db/dump.sql
