name: Docker Image CD

on:
  push:
    branches:
      - "master"
    paths:
      - "src/*"
      - "package.json"
      - "Dockerfile"

jobs:
  push-docker-image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
